### ISSUE TITLE
refactor source for version 1.1.1 (step 2)

### ISSUE THREAD

**Issue by hwclass** [hwclass/qrauth-client#8]
Steps to reproduce:

- [ ]  Integrate React library to use actively
- [ ]  Resolve issues with 3rd-party libraries (like socket.io and github.com/qrcodejs/qrcode.min.js)
- [ ]  Seperate every class within classes directory
- [ ]  Seperate every utility method within utils directory
- [ ]  Seperate every string constant within constants directory
- [ ]  Integrate [CSS Modules](https://github.com/css-modules/webpack-demo)
- [ ]  Write unit/functional tests with Jest + Enzyme
- [ ]  Add ESLint support
